language: cpp

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get install -qq libboost-all-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - mkdir build
  - cd build
  - sudo apt-get install cmake
  - cmake --version
  - cmake ..

script: make && ctest
